/**
 * Generated by Dalaran
 *   version: 0.0.61
 */
package org.ppj.pp.event.sample.service;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.ppj.mainstay.common.RouteArg;


public interface IRemoteSyncPPEventSampleService {
    
    public org.ppj.pp.event.sample.model.CommonResponse findUserById(Long userId);
    
    public org.ppj.pp.event.sample.model.CommonResponse addUser(Long number, String name, Integer age, Integer sex);
  
}
