/**
 * Generated by Dalaran
 *   version: 0.0.61
 */
package org.ppj.pp.event.sample.converter;

import java.nio.ByteBuffer;
import java.util.*;


public class CommonResponseConverter {

  public static org.ppj.pp.event.sample.model.CommonResponse transform(org.ppj.pp.event.sample.thrift.CommonResponse source) {
    org.ppj.pp.event.sample.model.CommonResponse target = new org.ppj.pp.event.sample.model.CommonResponse();
    if (null != source) {
      if (source.isSetCode()) {
        Integer _code_item = source.getCode();
        target.setCode(_code_item);
      }
      if (source.isSetMessage()) {
        String _message_item = source.getMessage();
        target.setMessage(_message_item);
      }
      if (source.isSetResult()) {
        String _result_item = source.getResult();
        target.setResult(_result_item);
      }
    }
    return target;
  }

  public static org.ppj.pp.event.sample.thrift.CommonResponse transform(org.ppj.pp.event.sample.model.CommonResponse source) {
    org.ppj.pp.event.sample.thrift.CommonResponse.Builder target = new org.ppj.pp.event.sample.thrift.CommonResponse.Builder();
    if (null != source) {
      if (source.getCode() != null) {
        Integer _code_item = source.getCode();
        target.setCode(_code_item);
      }
      if (source.getMessage() != null) {
        String _message_item = source.getMessage();
        target.setMessage(_message_item);
      }
      if (source.getResult() != null) {
        String _result_item = source.getResult();
        target.setResult(_result_item);
      }
    }
    return target.build();
  }
}
