/**
 * Generated by Dalaran
 *   version: 0.0.61
 */
package org.ppj.pp.event.sample.model;

import java.nio.ByteBuffer;
import java.util.*;


public class CommonResponse {

  private Integer code;
  private String message;
  private String result;

  public CommonResponse() {
  }

  public CommonResponse(Integer code, String message, String result) {
    this.code = code;
    this.message = message;
    this.result = result;
  }

  public void setCode(Integer code) {
    this.code = code;
  }

  public Integer getCode() {
    return this.code;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public String getMessage() {
    return this.message;
  }

  public void setResult(String result) {
    this.result = result;
  }

  public String getResult() {
    return this.result;
  }

  @Override
  public String toString() {
    return "CommonResponse(" +"code=" + this.code + ", " + "message=" + this.message + ", " + "result=" + this.result + ")";
  }

  @Override
  public int hashCode() {
    int hash = 1;
    hash = 31 * hash + (this.code == null ? 0 : this.code.hashCode());
    hash = 31 * hash + (this.message == null ? 0 : this.message.hashCode());
    hash = 31 * hash + (this.result == null ? 0 : this.result.hashCode());
    return hash;
  }

  @Override
  public boolean equals(Object other) {
    if (!(other instanceof CommonResponse)) {
      return false;
    }
    CommonResponse that = (CommonResponse) other;
    if (this.code == null) {
      if (that.code != null)
        return false;
    } else if (!this.code.equals(that.code)) {
      return false;
    }
    if (this.message == null) {
      if (that.message != null)
        return false;
    } else if (!this.message.equals(that.message)) {
      return false;
    }
    if (this.result == null) {
      if (that.result != null)
        return false;
    } else if (!this.result.equals(that.result)) {
      return false;
    }
    return true;
  }
}
