/**
 * Generated by Dalaran
 *   version: 0.0.61
 */
package org.ppj.pp.event.sample.ex;


public class PPEventSampleServiceException extends RuntimeException {

  /**
   *
   */
  private static final long serialVersionUID = 6568976777906556173L;
  
  /**
   * 
   */
  public PPEventSampleServiceException() {
  }

  /**
   * @param message
   */
  public PPEventSampleServiceException(String message) {
    super(message);
  }

  /**
   * @param cause
   */
  public PPEventSampleServiceException(Throwable cause) {
    super(cause);
  }

  /**
   * @param message
   * @param cause
   */
  public PPEventSampleServiceException(String message, Throwable cause) {
    super(message, cause);
  }

}
