/**
 * Generated by Dalaran
 *   version: 0.0.61
 */
package org.ppj.pp.event.sample.service.impl;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.lang.RuntimeException;

import org.springframework.beans.factory.annotation.Autowired;

import org.ppj.mainstay.rpc.thrift.TException;

import org.ppj.pp.event.sample.service.*;
import org.ppj.pp.event.sample.ex.*;


public class ThriftRemoteSyncPPEventSampleService implements IRemoteSyncPPEventSampleService {

  @Autowired
  private org.ppj.pp.event.sample.thrift.PPEventSampleService.Iface client;

  
  @Override
  public org.ppj.pp.event.sample.model.CommonResponse findUserById(Long userId) {
    try {
      Long _userId_arg_item = userId;
  
      org.ppj.pp.event.sample.thrift.CommonResponse client_result = client.findUserById(_userId_arg_item);
      if (client_result == null) {
        return null;
      }
  
      org.ppj.pp.event.sample.model.CommonResponse _client_result_result_item = org.ppj.pp.event.sample.converter.CommonResponseConverter.transform(client_result);
      return _client_result_result_item;
    } catch (TException e) {
      throw new PPEventSampleServiceException("call findUserById failed.", e);
    }
  }
  
  @Override
  public org.ppj.pp.event.sample.model.CommonResponse addUser(Long number, String name, Integer age, Integer sex) {
    try {
      Long _number_arg_item = number;
      String _name_arg_item = name;
      Integer _age_arg_item = age;
      Integer _sex_arg_item = sex;
  
      org.ppj.pp.event.sample.thrift.CommonResponse client_result = client.addUser(_number_arg_item, _name_arg_item, _age_arg_item, _sex_arg_item);
      if (client_result == null) {
        return null;
      }
  
      org.ppj.pp.event.sample.model.CommonResponse _client_result_result_item = org.ppj.pp.event.sample.converter.CommonResponseConverter.transform(client_result);
      return _client_result_result_item;
    } catch (TException e) {
      throw new PPEventSampleServiceException("call addUser failed.", e);
    }
  }
}
