/**
 * Generated by Dalaran
 *   version: 0.0.61
 */
package org.ppj.pp.event.sample.service.impl;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;

import org.ppj.mainstay.common.concurrent.FutureCallback;
import org.ppj.mainstay.common.concurrent.Futures;
import org.ppj.mainstay.common.concurrent.Future;
import org.ppj.mainstay.common.concurrent.SettableFuture;
import org.ppj.mainstay.rpc.thrift.TException;

import org.ppj.pp.event.sample.service.*;
import org.ppj.pp.event.sample.ex.*;


public class ThriftRemoteAsyncPPEventSampleService implements IRemoteAsyncPPEventSampleService {

  @Autowired
  private org.ppj.pp.event.sample.thrift.PPEventSampleService.FutureIface client;

  
  @Override
  public Future<org.ppj.pp.event.sample.model.CommonResponse> findUserById(Long userId) {
    Long _userId_arg_item = userId;
  
    Future<org.ppj.pp.event.sample.thrift.CommonResponse> client_result = client.findUserById(_userId_arg_item);
    final SettableFuture<org.ppj.pp.event.sample.model.CommonResponse> settableFuture = Futures.newSettableFuture();
    Futures.addCallback(client_result, new FutureCallback<org.ppj.pp.event.sample.thrift.CommonResponse>() {
  
      @Override
      public void onSuccess(org.ppj.pp.event.sample.thrift.CommonResponse client_result) {
        if (client_result == null) {
          settableFuture.set(null);
          return;
        }
        org.ppj.pp.event.sample.model.CommonResponse _client_result_result_item = org.ppj.pp.event.sample.converter.CommonResponseConverter.transform(client_result);
        settableFuture.set(_client_result_result_item);
  
  
      }
  
      @Override
      public void onFailure(Throwable t) {
        settableFuture.setException(t);
      }
    });
    return settableFuture;
  }
  
  @Override
  public Future<org.ppj.pp.event.sample.model.CommonResponse> addUser(Long number, String name, Integer age, Integer sex) {
    Long _number_arg_item = number;
    String _name_arg_item = name;
    Integer _age_arg_item = age;
    Integer _sex_arg_item = sex;
  
    Future<org.ppj.pp.event.sample.thrift.CommonResponse> client_result = client.addUser(_number_arg_item, _name_arg_item, _age_arg_item, _sex_arg_item);
    final SettableFuture<org.ppj.pp.event.sample.model.CommonResponse> settableFuture = Futures.newSettableFuture();
    Futures.addCallback(client_result, new FutureCallback<org.ppj.pp.event.sample.thrift.CommonResponse>() {
  
      @Override
      public void onSuccess(org.ppj.pp.event.sample.thrift.CommonResponse client_result) {
        if (client_result == null) {
          settableFuture.set(null);
          return;
        }
        org.ppj.pp.event.sample.model.CommonResponse _client_result_result_item = org.ppj.pp.event.sample.converter.CommonResponseConverter.transform(client_result);
        settableFuture.set(_client_result_result_item);
  
  
      }
  
      @Override
      public void onFailure(Throwable t) {
        settableFuture.setException(t);
      }
    });
    return settableFuture;
  }
}
