@startuml
title 核心业务处理流程
Caller -> BusinessSystem: doBusiness
BusinessSystem -> BusinessSystem: writeBusinessEntity
BusinessSystem ->PPEventFrameWork: applyEvent
XiEventFrameWork -> EventBus: publishEventMessage
EventBus -> EventBus: buildMethodInvocations
EventBus -> EventBus: buildXiEvents
EventBus -> PPEventMapper:insert
EventBus -> AsyncMethodInvoker:invoke
AsyncMethodInvoker -> AsyncDisruptor:ensureStart
AsyncDisruptor -> AsyncDisruptor:tryPublish

XiEventControlCenter--> EventHandleRecoverJob: triggerRecoverJob
activatePPEventControlCenter
EventHandleRecoverJob-> PPEventMapper: findNeedRetryEvents
EventHandleRecoverJob-> EventMethodProcessor: handle
deactivatePPEventControlCenter

XiEventControlCenter--> FailedEventWarnJob: triggerFailedEventWarnJob
activatePPEventControlCenter
FailedEventWarnJob-> PPEventMapper: findFailedEvents
FailedEventWarnJob-> FailedEventWarnJob: warnByDingding
deactivatePPEventControlCenter
@enduml