@startuml
title 核心业务处理流程
Caller -> BusinessSystem: doBusiness
BusinessSystem -> BusinessSystem: writeBusinessEntity
BusinessSystem ->PPEventFrameWork: applyEvent


PPEventFrameWork -> EventBus: publishEventMessage
EventBus -> EventBus: buildMethodInvocations
EventBus -> EventBus: buildPPEvents
EventBus -> PPEventMapper:insert
EventBus -> AsyncMethodInvoker:invoke
AsyncMethodInvoker -> AsyncDisruptor:ensureStart
AsyncDisruptor -> AsyncDisruptor:tryPublish

PPEventControlCenter--> EventHandleRecoverJob: triggerRecoverJob
activate PPEventControlCenter
EventHandleRecoverJob-> PPEventMapper: findNeedRetryEvents
EventHandleRecoverJob-> EventMethodProcessor: handle
deactivate PPEventControlCenter

PPEventControlCenter--> FailedEventWarnJob: triggerFailedEventWarnJob
activate PPEventControlCenter
FailedEventWarnJob-> PPEventMapper: findFailedEvents
FailedEventWarnJob-> FailedEventWarnJob: warnByDingding
deactivate PPEventControlCenter
@enduml