@startuml
title 系统启动流程
SpringApplication -> SpringApplication:run
SpringApplication -> AnnotationEventListenerBeanPostProcessor:postProcessAfterInitialization
opt hasEventHandlerMethod
    AnnotationEventListenerBeanPostProcessor->AnnotationEventListenerBeanPostProcessor:createEventListener
    AnnotationEventListenerBeanPostProcessor->EventBus:subscribe
    EventBus->EventBus:addEventListener
end
SpringApplication -> PPEventFrameworkInitializer:run
PPEventFrameworkInitializer -> RegisterService:initJob
RegisterService -> PPEventControlCenter:saveJobGroup
RegisterService -> PPEventControlCenter:saveEventHandleRecoverJobInfo
RegisterService -> PPEventControlCenter:saveEventFailedWarnJobInfo
@enduml