/**
 * Generated by Dalaran
 *   version: 0.0.61
 */
package org.ppj.pp.event.sample.thrift;

import java.nio.ByteBuffer;
import java.util.*;

import org.ppj.mainstay.common.MainstayCodecException;
import org.ppj.mainstay.common.Option;
import org.ppj.mainstay.common.RouteArg;
import org.ppj.mainstay.common.util.Utilities;
import org.ppj.mainstay.rpc.thrift.ThriftStruct;
import org.ppj.mainstay.rpc.thrift.ThriftStructCodec;
import org.ppj.mainstay.rpc.thrift.TException;
import org.ppj.mainstay.rpc.thrift.protocol.*;


public class CommonResponse implements ThriftStruct {
  private static final TStruct STRUCT = new TStruct("CommonResponse");
  private static final TField CodeField = new TField("code", TType.I32, (short) 1);
  final int code;
  boolean isSetCode;
  private static final TField MessageField = new TField("message", TType.STRING, (short) 2);
  final String message;
  boolean isSetMessage;
  private static final TField ResultField = new TField("result", TType.STRING, (short) 3);
  final String result;
  boolean isSetResult;

  public static class Builder {
    private int _code = 0;
    private boolean isSetCode = false;
    public Builder setCode(int value) {
      this._code = value;
        this.isSetCode = true;
      return this;
    }


    public boolean isSetCode() {
      return isSetCode;
    }

    public int getCode() {
      return this._code;
    }

    public Builder unsetCode() {
      this._code = 0;
      return this;
    }

    // 仅用于发送空字段到服务端
    public Builder emptyCode() {
      this._code = 0;
      this.isSetCode = true;
      return this;
    }

    private String _message = null;
    private boolean isSetMessage = false;
    public Builder setMessage(String value) {
      this._message = value;
      if (value != null) {
        this.isSetMessage = true;
      }
      return this;
    }


    public boolean isSetMessage() {
      return isSetMessage;
    }

    public String getMessage() {
      return this._message;
    }

    public Builder unsetMessage() {
      this._message = null;
      return this;
    }

    // 仅用于发送空字段到服务端
    public Builder emptyMessage() {
      this._message = null;
      this.isSetMessage = true;
      return this;
    }

    private String _result = null;
    private boolean isSetResult = false;
    public Builder setResult(String value) {
      this._result = value;
      if (value != null) {
        this.isSetResult = true;
      }
      return this;
    }


    public boolean isSetResult() {
      return isSetResult;
    }

    public String getResult() {
      return this._result;
    }

    public Builder unsetResult() {
      this._result = null;
      return this;
    }

    // 仅用于发送空字段到服务端
    public Builder emptyResult() {
      this._result = null;
      this.isSetResult = true;
      return this;
    }


    public CommonResponse build() {
      CommonResponse model = new CommonResponse(this._code, this._message, this._result);
      model.isSetCode = isSetCode;
      model.isSetMessage = isSetMessage;
      model.isSetResult = isSetResult;
      return model;
    }
  }

  public Builder copy() {
    Builder builder = new Builder();
    if (isSetCode) builder.setCode(this.code);
    if (isSetMessage) builder.setMessage(this.message);
    if (isSetResult) builder.setResult(this.result);
    return builder;
  }

  public static final ThriftStructCodec<CommonResponse> CODEC = new ThriftStructCodec<CommonResponse>() {
    @Override
    public CommonResponse decode(TProtocol _iprot) throws TException {
      Builder builder = new Builder();
      int code = 0;
      String message = null;
      String result = null;
      Boolean _done = false;
      _iprot.readStructBegin();
      while (!_done) {
        TField _field = _iprot.readFieldBegin();
        if (_field.type == TType.STOP) {
          _done = true;
        } else {
          switch (_field.id) {
            case 1: /* code */
              switch (_field.type) {
                case TType.I32:
                  Integer code_item;
                  code_item = _iprot.readI32();
                  code = code_item;
                  break;
                default:
                  TProtocolUtil.skip(_iprot, _field.type);
              }
              builder.setCode(code);
              break;
            case 2: /* message */
              switch (_field.type) {
                case TType.STRING:
                  String message_item;
                  message_item = _iprot.readString();
                  message = message_item;
                  break;
                default:
                  TProtocolUtil.skip(_iprot, _field.type);
              }
              builder.setMessage(message);
              break;
            case 3: /* result */
              switch (_field.type) {
                case TType.STRING:
                  String result_item;
                  result_item = _iprot.readString();
                  result = result_item;
                  break;
                default:
                  TProtocolUtil.skip(_iprot, _field.type);
              }
              builder.setResult(result);
              break;
            default:
              TProtocolUtil.skip(_iprot, _field.type);
          }
          _iprot.readFieldEnd();
        }
      }
      _iprot.readStructEnd();
      try {
        return builder.build();
      } catch (IllegalStateException stateEx) {
        throw new TProtocolException(stateEx.getMessage());
      }
    }

    @Override
    public void encode(CommonResponse struct, TProtocol oprot) throws TException {
      struct.write(oprot);
    }
  };

  public static CommonResponse decode(TProtocol _iprot) throws TException {
    return CODEC.decode(_iprot);
  }

  public static void encode(CommonResponse struct, TProtocol oprot) throws TException {
    CODEC.encode(struct, oprot);
  }

  CommonResponse(int code, String message, String result) {
    this.code = code;
    this.message = message;
    this.result = result;
  }


  public int getCode() {
    return this.code;
  }
  
  public boolean isSetCode() {
    return this.isSetCode;
  }
  public String getMessage() {
    return this.message;
  }
  
  public boolean isSetMessage() {
    return this.isSetMessage;
  }
  public String getResult() {
    return this.result;
  }
  
  public boolean isSetResult() {
    return this.isSetResult;
  }

  @Override
  public void write(TProtocol _oprot) throws TException {
    validate();
    _oprot.writeStructBegin(STRUCT);
    if (this.isSetCode) {
        _oprot.writeFieldBegin(CodeField);
        Integer code_item = code;
        _oprot.writeI32(code_item);
        _oprot.writeFieldEnd();
    }
    if (this.isSetMessage) {
      if (message != null) {
        _oprot.writeFieldBegin(MessageField);
        String message_item = message;
        _oprot.writeString(message_item);
        _oprot.writeFieldEnd();
      }
    }
    if (this.isSetResult) {
      if (result != null) {
        _oprot.writeFieldBegin(ResultField);
        String result_item = result;
        _oprot.writeString(result_item);
        _oprot.writeFieldEnd();
      }
    }
    _oprot.writeFieldStop();
    _oprot.writeStructEnd();
  }

  private void validate() throws TProtocolException {
  }


  @Override
  public boolean equals(Object other) {
    if (!(other instanceof CommonResponse)) {
      return false;
    }
    CommonResponse that = (CommonResponse) other;
    if (this.code != that.code) {
      return false;
    }
    if (this.message == null) {
      if (that.message != null)
        return false;
    } else if (!this.message.equals(that.message)) {
      return false;
    }
    if (this.result == null) {
      if (that.result != null)
        return false;
    } else if (!this.result.equals(that.result)) {
      return false;
    }
    return true;
  }

  private int hash(Object... values) {
    return java.util.Arrays.hashCode(values);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CommonResponse(");
    if (this.isSetCode) {
      sb.append("code=");
      sb.append(this.code);
      sb.append(", ");
    }
    if (this.isSetMessage) {
      sb.append("message=");
      sb.append(this.message);
      sb.append(", ");
    }
    if (this.isSetResult) {
      sb.append("result=");
      sb.append(this.result);
      sb.append(", ");
    }
    sb.append(")");
    return sb.toString();
  }

  @Override
  public int hashCode() {
    int hash = 1;
    hash = 31 * hash + hash * hash(this.code);
    hash = 31 * hash + hash * (this.message == null ? 0 : this.message.hashCode());
    hash = 31 * hash + hash * (this.result == null ? 0 : this.result.hashCode());
    return hash;
  }
}
