/**
 * Generated by Dalaran
 *   version: 0.0.61
 */
package org.ppj.pp.event.sample.thrift;

import java.nio.ByteBuffer;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.ppj.mainstay.common.MainstayCodecException;
import org.ppj.mainstay.common.Option;
import org.ppj.mainstay.common.RouteArg;
import org.ppj.mainstay.common.concurrent.FutureCallback;
import org.ppj.mainstay.common.concurrent.Futures;
import org.ppj.mainstay.common.concurrent.Future;
import org.ppj.mainstay.common.concurrent.SettableFuture;
import org.ppj.mainstay.common.util.Utilities;
import org.ppj.mainstay.rpc.thrift.processor.TBaseProcessor;
import org.ppj.mainstay.rpc.thrift.processor.TProcessFunction;
import org.ppj.mainstay.rpc.thrift.processor.TProcessor;
import org.ppj.mainstay.rpc.thrift.TCodec;
import org.ppj.mainstay.rpc.thrift.TFutureClient;
import org.ppj.mainstay.rpc.thrift.ThriftMessage;
import org.ppj.mainstay.rpc.thrift.ThriftStruct;
import org.ppj.mainstay.rpc.thrift.ThriftStructCodec;
import org.ppj.mainstay.rpc.thrift.TApplicationException;
import org.ppj.mainstay.rpc.thrift.TException;
import org.ppj.mainstay.rpc.thrift.protocol.TField;
import org.ppj.mainstay.rpc.thrift.protocol.TList;
import org.ppj.mainstay.rpc.thrift.protocol.TMap;
import org.ppj.mainstay.rpc.thrift.protocol.TSet;
import org.ppj.mainstay.rpc.thrift.protocol.TProtocol;
import org.ppj.mainstay.rpc.thrift.protocol.TProtocolException;
import org.ppj.mainstay.rpc.thrift.protocol.TProtocolFactory;
import org.ppj.mainstay.rpc.thrift.protocol.TProtocolUtil;
import org.ppj.mainstay.rpc.thrift.protocol.TStruct;
import org.ppj.mainstay.rpc.thrift.protocol.TType;
import org.ppj.mainstay.transport.Client;
import org.ppj.mainstay.transport.Message;


public class PPEventSampleService {
  public static interface Iface {
    
    public CommonResponse findUserById(long userId) throws TException;
    
    public CommonResponse addUser(long number, String name, int age, int sex) throws TException;
  }

  public static interface FutureIface {
    
    public Future<CommonResponse> findUserById(long userId);
    
    public Future<CommonResponse> addUser(long number, String name, int age, int sex);
  }
  
  public static class FindUserById {
  public static class Args implements ThriftStruct {
      private static final TStruct STRUCT = new TStruct("findUserById_args");
      private static final TField UserIdField = new TField("userId", TType.I64, (short) 1);
      final long userId;
      boolean isSetUserId;
    
      public static class Builder {
        private long _userId = 0L;
        private boolean isSetUserId = false;
        public Builder setUserId(long value) {
          this._userId = value;
            this.isSetUserId = true;
          return this;
        }
    
    
        public boolean isSetUserId() {
          return isSetUserId;
        }
    
        public long getUserId() {
          return this._userId;
        }
    
        public Builder unsetUserId() {
          this._userId = 0L;
          return this;
        }
    
        // 仅用于发送空字段到服务端
        public Builder emptyUserId() {
          this._userId = 0L;
          this.isSetUserId = true;
          return this;
        }
    
    
        public Args build() {
          Args model = new Args(this._userId);
          model.isSetUserId = isSetUserId;
          return model;
        }
      }
    
      public Builder copy() {
        Builder builder = new Builder();
        if (isSetUserId) builder.setUserId(this.userId);
        return builder;
      }
    
      public static final ThriftStructCodec<Args> CODEC = new ThriftStructCodec<Args>() {
        @Override
        public Args decode(TProtocol _iprot) throws TException {
          Builder builder = new Builder();
          long userId = 0L;
          Boolean _done = false;
          _iprot.readStructBegin();
          while (!_done) {
            TField _field = _iprot.readFieldBegin();
            if (_field.type == TType.STOP) {
              _done = true;
            } else {
              switch (_field.id) {
                case 1: /* userId */
                  switch (_field.type) {
                    case TType.I64:
                      Long userId_item;
                      userId_item = _iprot.readI64();
                      userId = userId_item;
                      break;
                    default:
                      TProtocolUtil.skip(_iprot, _field.type);
                  }
                  builder.setUserId(userId);
                  break;
                default:
                  TProtocolUtil.skip(_iprot, _field.type);
              }
              _iprot.readFieldEnd();
            }
          }
          _iprot.readStructEnd();
          try {
            return builder.build();
          } catch (IllegalStateException stateEx) {
            throw new TProtocolException(stateEx.getMessage());
          }
        }
    
        @Override
        public void encode(Args struct, TProtocol oprot) throws TException {
          struct.write(oprot);
        }
      };
    
      public static Args decode(TProtocol _iprot) throws TException {
        return CODEC.decode(_iprot);
      }
    
      public static void encode(Args struct, TProtocol oprot) throws TException {
        CODEC.encode(struct, oprot);
      }
    
      Args(long userId) {
        this.userId = userId;
      }
    
    
      public long getUserId() {
        return this.userId;
      }
  
      public boolean isSetUserId() {
        return this.isSetUserId;
      }
    
      @Override
      public void write(TProtocol _oprot) throws TException {
        validate();
        _oprot.writeStructBegin(STRUCT);
        if (this.isSetUserId) {
            _oprot.writeFieldBegin(UserIdField);
            Long userId_item = userId;
            _oprot.writeI64(userId_item);
            _oprot.writeFieldEnd();
        }
        _oprot.writeFieldStop();
        _oprot.writeStructEnd();
      }
    
      private void validate() throws TProtocolException {
      }
    
    
      @Override
      public boolean equals(Object other) {
        if (!(other instanceof Args)) {
          return false;
        }
        Args that = (Args) other;
        if (this.userId != that.userId) {
          return false;
        }
        return true;
      }
    
      private int hash(Object... values) {
        return java.util.Arrays.hashCode(values);
      }
    
      @Override
      public String toString() {
        StringBuilder sb = new StringBuilder("Args(");
        if (this.isSetUserId) {
          sb.append("userId=");
          sb.append(this.userId);
          sb.append(", ");
        }
        sb.append(")");
        return sb.toString();
      }
    
      @Override
      public int hashCode() {
        int hash = 1;
        hash = 31 * hash + hash * hash(this.userId);
        return hash;
      }
    }
  public static class Result implements ThriftStruct {
      private static final TStruct STRUCT = new TStruct("findUserById_result");
      private static final TField SuccessField = new TField("success", TType.STRUCT, (short) 0);
      final Option<CommonResponse> success;
      boolean isSetSuccess;
    
      public static class Builder {
        private CommonResponse _success = null;
        private boolean isSetSuccess = false;
        public Builder setSuccess(CommonResponse value) {
          this._success = value;
          if (value != null) {
            this.isSetSuccess = true;
          }
          return this;
        }
    
        public Builder setSuccessOpt(Option<CommonResponse> value) {
          if (value.isDefined()) {
            this._success = value.get();
            this.isSetSuccess = true;
          }
          return this;
        }
    
        public boolean isSetSuccess() {
          return isSetSuccess;
        }
    
        public CommonResponse getSuccess() {
          return this._success;
        }
    
        public Builder unsetSuccess() {
          this._success = null;
          return this;
        }
    
        // 仅用于发送空字段到服务端
        public Builder emptySuccess() {
          this._success = null;
          this.isSetSuccess = true;
          return this;
        }
    
    
        public Result build() {
          Result model = new Result(Option.fromNullable(this._success) );
          model.isSetSuccess = isSetSuccess;
          return model;
        }
      }
    
      public Builder copy() {
        Builder builder = new Builder();
        if (this.success.isDefined() && isSetSuccess) builder.setSuccess(this.success.get());
        return builder;
      }
    
      public static final ThriftStructCodec<Result> CODEC = new ThriftStructCodec<Result>() {
        @Override
        public Result decode(TProtocol _iprot) throws TException {
          Builder builder = new Builder();
          CommonResponse success = null;
          Boolean _done = false;
          _iprot.readStructBegin();
          while (!_done) {
            TField _field = _iprot.readFieldBegin();
            if (_field.type == TType.STOP) {
              _done = true;
            } else {
              switch (_field.id) {
                case 0: /* success */
                  switch (_field.type) {
                    case TType.STRUCT:
                      CommonResponse success_item;
                      success_item = org.ppj.pp.event.sample.thrift.CommonResponse.decode(_iprot);
                      success = success_item;
                      break;
                    default:
                      TProtocolUtil.skip(_iprot, _field.type);
                  }
                  builder.setSuccess(success);
                  break;
                default:
                  TProtocolUtil.skip(_iprot, _field.type);
              }
              _iprot.readFieldEnd();
            }
          }
          _iprot.readStructEnd();
          try {
            return builder.build();
          } catch (IllegalStateException stateEx) {
            throw new TProtocolException(stateEx.getMessage());
          }
        }
    
        @Override
        public void encode(Result struct, TProtocol oprot) throws TException {
          struct.write(oprot);
        }
      };
    
      public static Result decode(TProtocol _iprot) throws TException {
        return CODEC.decode(_iprot);
      }
    
      public static void encode(Result struct, TProtocol oprot) throws TException {
        CODEC.encode(struct, oprot);
      }
    
      Result(Option<CommonResponse> success) {
        this.success = success;
      }
    
    
      public CommonResponse getSuccess() {
        return this.success.get();
      }
        public Option<CommonResponse> getSuccessOpt() {
        return this.success;
      }
  
      public boolean isSetSuccess() {
        return this.isSetSuccess;
      }
    
      @Override
      public void write(TProtocol _oprot) throws TException {
        validate();
        _oprot.writeStructBegin(STRUCT);
        if (this.isSetSuccess) {
          if (success.isDefined()) {
            _oprot.writeFieldBegin(SuccessField);
            org.ppj.pp.event.sample.thrift.CommonResponse success_item = success.get();
            success_item.write(_oprot);
            _oprot.writeFieldEnd();
          }
        }
        _oprot.writeFieldStop();
        _oprot.writeStructEnd();
      }
    
      private void validate() throws TProtocolException {
      }
    
    
      @Override
      public boolean equals(Object other) {
        if (!(other instanceof Result)) {
          return false;
        }
        Result that = (Result) other;
        if (this.success == null) {
          if (that.success != null)
            return false;
        } else if (!this.success.equals(that.success)) {
          return false;
        }
        return true;
      }
    
      private int hash(Object... values) {
        return java.util.Arrays.hashCode(values);
      }
    
      @Override
      public String toString() {
        StringBuilder sb = new StringBuilder("Result(");
        if (this.isSetSuccess) {
          sb.append("success=");
          sb.append(this.success);
          sb.append(", ");
        }
        sb.append(")");
        return sb.toString();
      }
    
      @Override
      public int hashCode() {
        int hash = 1;
        hash = 31 * hash + hash * (this.success.isDefined() ? this.success.get().hashCode() : 0);
        return hash;
      }
    }
  }
  public static class AddUser {
  public static class Args implements ThriftStruct {
      private static final TStruct STRUCT = new TStruct("addUser_args");
      private static final TField NumberField = new TField("number", TType.I64, (short) 1);
      final long number;
      boolean isSetNumber;
      private static final TField NameField = new TField("name", TType.STRING, (short) 2);
      final String name;
      boolean isSetName;
      private static final TField AgeField = new TField("age", TType.I32, (short) 3);
      final int age;
      boolean isSetAge;
      private static final TField SexField = new TField("sex", TType.I32, (short) 4);
      final int sex;
      boolean isSetSex;
    
      public static class Builder {
        private long _number = 0L;
        private boolean isSetNumber = false;
        public Builder setNumber(long value) {
          this._number = value;
            this.isSetNumber = true;
          return this;
        }
    
    
        public boolean isSetNumber() {
          return isSetNumber;
        }
    
        public long getNumber() {
          return this._number;
        }
    
        public Builder unsetNumber() {
          this._number = 0L;
          return this;
        }
    
        // 仅用于发送空字段到服务端
        public Builder emptyNumber() {
          this._number = 0L;
          this.isSetNumber = true;
          return this;
        }
    
        private String _name = null;
        private boolean isSetName = false;
        public Builder setName(String value) {
          this._name = value;
          if (value != null) {
            this.isSetName = true;
          }
          return this;
        }
    
    
        public boolean isSetName() {
          return isSetName;
        }
    
        public String getName() {
          return this._name;
        }
    
        public Builder unsetName() {
          this._name = null;
          return this;
        }
    
        // 仅用于发送空字段到服务端
        public Builder emptyName() {
          this._name = null;
          this.isSetName = true;
          return this;
        }
    
        private int _age = 0;
        private boolean isSetAge = false;
        public Builder setAge(int value) {
          this._age = value;
            this.isSetAge = true;
          return this;
        }
    
    
        public boolean isSetAge() {
          return isSetAge;
        }
    
        public int getAge() {
          return this._age;
        }
    
        public Builder unsetAge() {
          this._age = 0;
          return this;
        }
    
        // 仅用于发送空字段到服务端
        public Builder emptyAge() {
          this._age = 0;
          this.isSetAge = true;
          return this;
        }
    
        private int _sex = 0;
        private boolean isSetSex = false;
        public Builder setSex(int value) {
          this._sex = value;
            this.isSetSex = true;
          return this;
        }
    
    
        public boolean isSetSex() {
          return isSetSex;
        }
    
        public int getSex() {
          return this._sex;
        }
    
        public Builder unsetSex() {
          this._sex = 0;
          return this;
        }
    
        // 仅用于发送空字段到服务端
        public Builder emptySex() {
          this._sex = 0;
          this.isSetSex = true;
          return this;
        }
    
    
        public Args build() {
          Args model = new Args(this._number, this._name, this._age, this._sex);
          model.isSetNumber = isSetNumber;
          model.isSetName = isSetName;
          model.isSetAge = isSetAge;
          model.isSetSex = isSetSex;
          return model;
        }
      }
    
      public Builder copy() {
        Builder builder = new Builder();
        if (isSetNumber) builder.setNumber(this.number);
        if (isSetName) builder.setName(this.name);
        if (isSetAge) builder.setAge(this.age);
        if (isSetSex) builder.setSex(this.sex);
        return builder;
      }
    
      public static final ThriftStructCodec<Args> CODEC = new ThriftStructCodec<Args>() {
        @Override
        public Args decode(TProtocol _iprot) throws TException {
          Builder builder = new Builder();
          long number = 0L;
          String name = null;
          int age = 0;
          int sex = 0;
          Boolean _done = false;
          _iprot.readStructBegin();
          while (!_done) {
            TField _field = _iprot.readFieldBegin();
            if (_field.type == TType.STOP) {
              _done = true;
            } else {
              switch (_field.id) {
                case 1: /* number */
                  switch (_field.type) {
                    case TType.I64:
                      Long number_item;
                      number_item = _iprot.readI64();
                      number = number_item;
                      break;
                    default:
                      TProtocolUtil.skip(_iprot, _field.type);
                  }
                  builder.setNumber(number);
                  break;
                case 2: /* name */
                  switch (_field.type) {
                    case TType.STRING:
                      String name_item;
                      name_item = _iprot.readString();
                      name = name_item;
                      break;
                    default:
                      TProtocolUtil.skip(_iprot, _field.type);
                  }
                  builder.setName(name);
                  break;
                case 3: /* age */
                  switch (_field.type) {
                    case TType.I32:
                      Integer age_item;
                      age_item = _iprot.readI32();
                      age = age_item;
                      break;
                    default:
                      TProtocolUtil.skip(_iprot, _field.type);
                  }
                  builder.setAge(age);
                  break;
                case 4: /* sex */
                  switch (_field.type) {
                    case TType.I32:
                      Integer sex_item;
                      sex_item = _iprot.readI32();
                      sex = sex_item;
                      break;
                    default:
                      TProtocolUtil.skip(_iprot, _field.type);
                  }
                  builder.setSex(sex);
                  break;
                default:
                  TProtocolUtil.skip(_iprot, _field.type);
              }
              _iprot.readFieldEnd();
            }
          }
          _iprot.readStructEnd();
          try {
            return builder.build();
          } catch (IllegalStateException stateEx) {
            throw new TProtocolException(stateEx.getMessage());
          }
        }
    
        @Override
        public void encode(Args struct, TProtocol oprot) throws TException {
          struct.write(oprot);
        }
      };
    
      public static Args decode(TProtocol _iprot) throws TException {
        return CODEC.decode(_iprot);
      }
    
      public static void encode(Args struct, TProtocol oprot) throws TException {
        CODEC.encode(struct, oprot);
      }
    
      Args(long number, String name, int age, int sex) {
        this.number = number;
        this.name = name;
        this.age = age;
        this.sex = sex;
      }
    
    
      public long getNumber() {
        return this.number;
      }
  
      public boolean isSetNumber() {
        return this.isSetNumber;
      }
      public String getName() {
        return this.name;
      }
  
      public boolean isSetName() {
        return this.isSetName;
      }
      public int getAge() {
        return this.age;
      }
  
      public boolean isSetAge() {
        return this.isSetAge;
      }
      public int getSex() {
        return this.sex;
      }
  
      public boolean isSetSex() {
        return this.isSetSex;
      }
    
      @Override
      public void write(TProtocol _oprot) throws TException {
        validate();
        _oprot.writeStructBegin(STRUCT);
        if (this.isSetNumber) {
            _oprot.writeFieldBegin(NumberField);
            Long number_item = number;
            _oprot.writeI64(number_item);
            _oprot.writeFieldEnd();
        }
        if (this.isSetName) {
          if (name != null) {
            _oprot.writeFieldBegin(NameField);
            String name_item = name;
            _oprot.writeString(name_item);
            _oprot.writeFieldEnd();
          }
        }
        if (this.isSetAge) {
            _oprot.writeFieldBegin(AgeField);
            Integer age_item = age;
            _oprot.writeI32(age_item);
            _oprot.writeFieldEnd();
        }
        if (this.isSetSex) {
            _oprot.writeFieldBegin(SexField);
            Integer sex_item = sex;
            _oprot.writeI32(sex_item);
            _oprot.writeFieldEnd();
        }
        _oprot.writeFieldStop();
        _oprot.writeStructEnd();
      }
    
      private void validate() throws TProtocolException {
      }
    
    
      @Override
      public boolean equals(Object other) {
        if (!(other instanceof Args)) {
          return false;
        }
        Args that = (Args) other;
        if (this.number != that.number) {
          return false;
        }
        if (this.name == null) {
          if (that.name != null)
            return false;
        } else if (!this.name.equals(that.name)) {
          return false;
        }
        if (this.age != that.age) {
          return false;
        }
        if (this.sex != that.sex) {
          return false;
        }
        return true;
      }
    
      private int hash(Object... values) {
        return java.util.Arrays.hashCode(values);
      }
    
      @Override
      public String toString() {
        StringBuilder sb = new StringBuilder("Args(");
        if (this.isSetNumber) {
          sb.append("number=");
          sb.append(this.number);
          sb.append(", ");
        }
        if (this.isSetName) {
          sb.append("name=");
          sb.append(this.name);
          sb.append(", ");
        }
        if (this.isSetAge) {
          sb.append("age=");
          sb.append(this.age);
          sb.append(", ");
        }
        if (this.isSetSex) {
          sb.append("sex=");
          sb.append(this.sex);
          sb.append(", ");
        }
        sb.append(")");
        return sb.toString();
      }
    
      @Override
      public int hashCode() {
        int hash = 1;
        hash = 31 * hash + hash * hash(this.number);
        hash = 31 * hash + hash * (this.name == null ? 0 : this.name.hashCode());
        hash = 31 * hash + hash * hash(this.age);
        hash = 31 * hash + hash * hash(this.sex);
        return hash;
      }
    }
  public static class Result implements ThriftStruct {
      private static final TStruct STRUCT = new TStruct("addUser_result");
      private static final TField SuccessField = new TField("success", TType.STRUCT, (short) 0);
      final Option<CommonResponse> success;
      boolean isSetSuccess;
    
      public static class Builder {
        private CommonResponse _success = null;
        private boolean isSetSuccess = false;
        public Builder setSuccess(CommonResponse value) {
          this._success = value;
          if (value != null) {
            this.isSetSuccess = true;
          }
          return this;
        }
    
        public Builder setSuccessOpt(Option<CommonResponse> value) {
          if (value.isDefined()) {
            this._success = value.get();
            this.isSetSuccess = true;
          }
          return this;
        }
    
        public boolean isSetSuccess() {
          return isSetSuccess;
        }
    
        public CommonResponse getSuccess() {
          return this._success;
        }
    
        public Builder unsetSuccess() {
          this._success = null;
          return this;
        }
    
        // 仅用于发送空字段到服务端
        public Builder emptySuccess() {
          this._success = null;
          this.isSetSuccess = true;
          return this;
        }
    
    
        public Result build() {
          Result model = new Result(Option.fromNullable(this._success) );
          model.isSetSuccess = isSetSuccess;
          return model;
        }
      }
    
      public Builder copy() {
        Builder builder = new Builder();
        if (this.success.isDefined() && isSetSuccess) builder.setSuccess(this.success.get());
        return builder;
      }
    
      public static final ThriftStructCodec<Result> CODEC = new ThriftStructCodec<Result>() {
        @Override
        public Result decode(TProtocol _iprot) throws TException {
          Builder builder = new Builder();
          CommonResponse success = null;
          Boolean _done = false;
          _iprot.readStructBegin();
          while (!_done) {
            TField _field = _iprot.readFieldBegin();
            if (_field.type == TType.STOP) {
              _done = true;
            } else {
              switch (_field.id) {
                case 0: /* success */
                  switch (_field.type) {
                    case TType.STRUCT:
                      CommonResponse success_item;
                      success_item = org.ppj.pp.event.sample.thrift.CommonResponse.decode(_iprot);
                      success = success_item;
                      break;
                    default:
                      TProtocolUtil.skip(_iprot, _field.type);
                  }
                  builder.setSuccess(success);
                  break;
                default:
                  TProtocolUtil.skip(_iprot, _field.type);
              }
              _iprot.readFieldEnd();
            }
          }
          _iprot.readStructEnd();
          try {
            return builder.build();
          } catch (IllegalStateException stateEx) {
            throw new TProtocolException(stateEx.getMessage());
          }
        }
    
        @Override
        public void encode(Result struct, TProtocol oprot) throws TException {
          struct.write(oprot);
        }
      };
    
      public static Result decode(TProtocol _iprot) throws TException {
        return CODEC.decode(_iprot);
      }
    
      public static void encode(Result struct, TProtocol oprot) throws TException {
        CODEC.encode(struct, oprot);
      }
    
      Result(Option<CommonResponse> success) {
        this.success = success;
      }
    
    
      public CommonResponse getSuccess() {
        return this.success.get();
      }
        public Option<CommonResponse> getSuccessOpt() {
        return this.success;
      }
  
      public boolean isSetSuccess() {
        return this.isSetSuccess;
      }
    
      @Override
      public void write(TProtocol _oprot) throws TException {
        validate();
        _oprot.writeStructBegin(STRUCT);
        if (this.isSetSuccess) {
          if (success.isDefined()) {
            _oprot.writeFieldBegin(SuccessField);
            org.ppj.pp.event.sample.thrift.CommonResponse success_item = success.get();
            success_item.write(_oprot);
            _oprot.writeFieldEnd();
          }
        }
        _oprot.writeFieldStop();
        _oprot.writeStructEnd();
      }
    
      private void validate() throws TProtocolException {
      }
    
    
      @Override
      public boolean equals(Object other) {
        if (!(other instanceof Result)) {
          return false;
        }
        Result that = (Result) other;
        if (this.success == null) {
          if (that.success != null)
            return false;
        } else if (!this.success.equals(that.success)) {
          return false;
        }
        return true;
      }
    
      private int hash(Object... values) {
        return java.util.Arrays.hashCode(values);
      }
    
      @Override
      public String toString() {
        StringBuilder sb = new StringBuilder("Result(");
        if (this.isSetSuccess) {
          sb.append("success=");
          sb.append(this.success);
          sb.append(", ");
        }
        sb.append(")");
        return sb.toString();
      }
    
      @Override
      public int hashCode() {
        int hash = 1;
        hash = 31 * hash + hash * (this.success.isDefined() ? this.success.get().hashCode() : 0);
        return hash;
      }
    }
  }


  public static class Processor extends TBaseProcessor<Iface> implements TProcessor {
    private static final Logger LOG = LoggerFactory.getLogger(Processor.class);
    public Processor(Iface iface) {
      super(iface, getProcessMap(new HashMap<String, TProcessFunction<Iface, ? extends ThriftStruct>>()));
    }
  
    public Processor(Iface iface, Map<String, TProcessFunction<Iface, ? extends ThriftStruct>> processMap) {
      super(iface, getProcessMap(processMap));
    }
    
    private static <I extends Iface> Map<String,  TProcessFunction<Iface, ? extends ThriftStruct>> getProcessMap(Map<String, TProcessFunction<Iface, ? extends ThriftStruct>> processMap) {
      processMap.put("findUserById", new FindUserByIdFunction());
      processMap.put("addUser", new AddUserFunction());
      return processMap;
    }
    private static class FindUserByIdFunction extends TProcessFunction<Iface, FindUserById.Args> {
      public FindUserByIdFunction() {
        super("findUserById");
      }
    
      @Override
      protected boolean isOneway() {
        return false;
      }
    
      @Override
      public ThriftStruct getResult(Iface iface, FindUserById.Args args) throws TException {
        FindUserById.Result.Builder builder = new FindUserById.Result.Builder();
        CommonResponse result = iface.findUserById(args.userId);
        builder.setSuccess(result);
        return builder.build();
      }
    }
    private static class AddUserFunction extends TProcessFunction<Iface, AddUser.Args> {
      public AddUserFunction() {
        super("addUser");
      }
    
      @Override
      protected boolean isOneway() {
        return false;
      }
    
      @Override
      public ThriftStruct getResult(Iface iface, AddUser.Args args) throws TException {
        AddUser.Result.Builder builder = new AddUser.Result.Builder();
        CommonResponse result = iface.addUser(args.number, args.name, args.age, args.sex);
        builder.setSuccess(result);
        return builder.build();
      }
    }
  }
  
  
  public static class FutureClient extends TFutureClient implements FutureIface {
    private static final Logger LOG = LoggerFactory.getLogger(FutureClient.class);

    public FutureClient(Client client) {
      super(client);
    }
    
    @Override
    public Future<CommonResponse> findUserById(long userId) {
      FindUserById.Args.Builder builder = new FindUserById.Args.Builder();
      builder.setUserId(userId);
      FindUserById.Args args = builder.build();
      ThriftMessage request = encodeRequest("findUserById", args);
      if (LOG.isDebugEnabled()) {
        LOG.debug("send thrift message {}",request);
      }
      Future<Message> responseFuture = client.send(request);
      final SettableFuture<CommonResponse> settableFuture = Futures.newSettableFuture(request);
      Futures.addCallback(responseFuture, new FutureCallback<Message>() {
    
        @Override
        public void onSuccess(Message response) {
          FindUserById.Result result = null;
          try {
            ThriftMessage thriftMessage = (ThriftMessage) response;
            if (LOG.isDebugEnabled()) {
              LOG.debug("receive thrift message {}", thriftMessage);
            }
            result = decodeResponse(thriftMessage);
          } catch (Throwable e) {
            settableFuture.setException(e);
            return;
          }
          if (result.isSetSuccess()) {
            settableFuture.set(result.getSuccess());
            return;
          }
          settableFuture.set(null);
        }
    
        @Override
        public void onFailure(Throwable t) {
          settableFuture.setException(t);
        }
      });
      return settableFuture;
    }
    
    @Override
    public Future<CommonResponse> addUser(long number, String name, int age, int sex) {
      AddUser.Args.Builder builder = new AddUser.Args.Builder();
      builder.setNumber(number);
      builder.setName(name);
      builder.setAge(age);
      builder.setSex(sex);
      AddUser.Args args = builder.build();
      ThriftMessage request = encodeRequest("addUser", args);
      if (LOG.isDebugEnabled()) {
        LOG.debug("send thrift message {}",request);
      }
      Future<Message> responseFuture = client.send(request);
      final SettableFuture<CommonResponse> settableFuture = Futures.newSettableFuture(request);
      Futures.addCallback(responseFuture, new FutureCallback<Message>() {
    
        @Override
        public void onSuccess(Message response) {
          AddUser.Result result = null;
          try {
            ThriftMessage thriftMessage = (ThriftMessage) response;
            if (LOG.isDebugEnabled()) {
              LOG.debug("receive thrift message {}", thriftMessage);
            }
            result = decodeResponse(thriftMessage);
          } catch (Throwable e) {
            settableFuture.setException(e);
            return;
          }
          if (result.isSetSuccess()) {
            settableFuture.set(result.getSuccess());
            return;
          }
          settableFuture.set(null);
        }
    
        @Override
        public void onFailure(Throwable t) {
          settableFuture.setException(t);
        }
      });
      return settableFuture;
    }
  }
  
  public static class ArgCodec extends TCodec {
    
    public ArgCodec(){
      super(getArgsCodecMap(new HashMap<String, ThriftStructCodec>()));
    }
    
    public static final Map<String, ThriftStructCodec> getArgsCodecMap(Map<String, ThriftStructCodec> codecMap) {
      codecMap.put("findUserById", FindUserById.Args.CODEC);
      codecMap.put("addUser", AddUser.Args.CODEC);
      return codecMap;
    }
  }
  public static class ResultCodec extends TCodec {
    
    public ResultCodec(){
      super(getResultCodecMap(new HashMap<String, ThriftStructCodec>()));
    }
    
    public static final Map<String, ThriftStructCodec> getResultCodecMap(Map<String, ThriftStructCodec> codecMap) {
      codecMap.put("findUserById", FindUserById.Result.CODEC);
      codecMap.put("addUser", AddUser.Result.CODEC);
      return codecMap;
    }
  }
}
